name: TestAction
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        run: git checkout master
      - name: Dir
        run: dir
      - name: Test
        run: python test_Car.py
