name: TestAction
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Dir_T
        run: dir
      - name: Test
        run: python -m unittest test_Car.py
